name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Execute static review
      run: npm run lint
    - name: Run Playwright tests
      env:
        BASE_URL: ${{ secrets.BASE_URL }}
        VALID_USER: ${{ secrets.VALID_USER }}
        LOCKED_USER: ${{ secrets.LOCKED_USER }}
        PROBLEM_USER: ${{ secrets.PROBLEM_USER }}
        GLITCHED_USER: ${{ secrets.GLITCHED_USER }}
        ERROR_USER: ${{ secrets.ERROR_USER }}
        VISUAL_USER: ${{ secrets.VISUAL_USER }}
        VALID_PASSWORD: ${{ secrets.VALID_PASSWORD }}
        INVALID_PASSWORD: ${{ secrets.INVALID_PASSWORD }}
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
    - name: Generate Allure Report
      run: npx allure generate allure-results --clean -o allure-report
    - name: Upload Allure Report
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: allure-report
        path: allure-report